# Generated by Django 4.2 on 2024-02-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_verified_user_verify_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verify_code',
        ),
        migrations.AddField(
            model_name='user',
            name='verify_email',
            field=models.CharField(default='6885', max_length=4, verbose_name='Код вeрификации'),
        ),
    ]
