# Generated by Django 4.2 on 2024-02-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_verify_code_user_verify_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verify_email',
        ),
        migrations.AddField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default='5131', max_length=4, verbose_name='Код вeрификации'),
        ),
    ]
