# Generated by Django 5.0 on 2024-01-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('product_description', models.TextField(blank=True, max_length=100, null=True, verbose_name='Описание')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_image/', verbose_name='Изображение (превью)')),
                ('product_category', models.CharField(max_length=100, verbose_name='Категория')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена за штуку')),
                ('product_date_of_creation', models.DateField()),
                ('product_date_of_modification', models.DateField()),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ('product_name',),
            },
        ),
    ]
